### ISSUE TITLE
Dirty database version 50

### ISSUE THREAD

**Issue by bartengine27** [kolesaev/ansible-role-harbor#1]
Dear,

  Thanks for your role!

  After running the role, I noticed the following error:

`
2024-07-01T16:15:36Z [INFO] [/common/dao/pgsql.go:135]: Upgrading schema for pgsql ...
2024-07-01T16:15:36Z [ERROR] [/common/dao/pgsql.go:140]: Failed to upgrade schema, error: "Dirty database version 50. Fix and force version."
2024-07-01T16:15:36Z [FATAL] [/core/main.go:198]: failed to migrate the database, error: Dirty database version 50. Fix and force version.
`

in goharbor/harbor-core:v2.10.0 on Ubuntu 22.04.4 LTS.

  Any idea what might be going wrong?

Thanks,
Bart

**Comment by bartengine27** [comment]
Solved with:

```
#connect to the postgresql
psql
#list tables
\l
connect to registry db
\c registry
#go db migration issue - XXXX is displayed in the goharbor/harbor-core logs
update schema_migrations set dirty=false where version=XXXX;
#default admin - Harbor1234 password - password set in the role did not work
update harbor_user set salt='J6Duybf2UcRhKchR06VbJWimv31xrlnN', password='d5942a4407756fee428ec889cb9c4830' where user_id = 1;
```

**Comment by kolesaev** [comment]
Hi,

I'm happy to hear you solved your issue. 
It's possible that there will be Harbor version upgrade/downgrade issues like you had. In these cases if you need to keep your previous data then try to find a solution on the internet; but if you don't need to keep your data then you are able to clean Harbor related docker volumes.
This role was originally designed to install and configure harbor instance, also it's possible to reconfigure an instance prepared with this role and i didn't tried to update/upgrade Harbor version. 
If anyone use this role to upgrade their harbor version i would suggest to look into official instructions from https://goharbor.io/docs/latest/administration/upgrade/. 
I possibly will add upgrade feature in the near future

BR.

**Comment by bartengine27** [comment]
Dear Kolesaev,

  Thanks for the feedback!

  The "go db migration" error was caused by an invalid proxy setting. After correcting the proxy settings and making some adjustments in the example role, your role executed flawlessly. 

Thanks!
Bart

```
   - role: kolesaev.harbor
      vars:
        harbor_version: "2.11.0"
        harbor_installation_type: offline
        harbor_parent_dir: /data
        harbor_data_dir: /data/harbor_data
        harbor_enable_trivy: true
        harbor_force_install: True
        harbor_iface_ip: 192.168.81.71
        #harbor_iface_ip: 127.0.0.1
        harbor_external_url: "https://{{ inventory_hostname }}"
        #harbor_admin_password: "{{ lookup('ansible.builtin.env', 'HARBOR_ADMIN_PWD') | default('Harbor12345') }}"
        harbor_admin_password: "Harbor12345"
        harbor_http_port: 5680
        harbor_https_port: 5643

        harbor_projects_to_remove:
          - library

        harbor_users:
          - name: "user-one"
            email: "email@example.com"
            password: "Harbor12345" # The password can be set once using this role, it will not be updated after changing the value
            realname: "user"
            comment: "comment"

        # harbor_registries:
        #   - url: "https://hub.docker.com"
        #     name: "docker-hub"
        #     type: "docker-hub"

        harbor_gc:
          type: Custom
          schedule: 0 0 1 * * *
          delete_untagged: false
          workers: 2  

        harbor_projects:

          - name: "new-project"
            auto_scan: yes
            public: no
            retention_policy:
              schedule: Hourly
              rules:
                - repositories_mask_type: "matching"
                  repositories_mask: "**"
                  tags_mask_type: "matching"
                  tags_mask: "dev-*"
                  rule_type: "pushed_by_days"
                  rule_value: 30

          - name: "docker-hub"
            public: yes
            proxy_registry: "docker-hub"

        harbor_members:
          - project: "new-project"
            name: "user-one"
            role_id: 2
```
